const TEST_USER = "TEST_USER";
const SET_SIGNED_IN = "SET_SIGNED_IN";
const SIGN_IN_USER = "SIGN_IN_USER";
const SET_PAGE = "SET_PAGE";
const SET_BOOKS = "SET_BOOKS";
const SET_GOOGLE_DATA = "SET_GOOGLE_DATA";
const SET_CURRENT_BOOK = "SET_CURRENT_BOOK";
const ADD_USER_BOOK = "ADD_USER_BOOK";
const EDIT_SHELVES = "EDIT_SHELVES";
const SET_SEARCH = "SET_SEARCH";
const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export {
  TEST_USER,
  SET_SIGNED_IN,
  SIGN_IN_USER,
  SET_PAGE,
  SET_BOOKS,
  SET_GOOGLE_DATA,
  SET_CURRENT_BOOK,
  ADD_USER_BOOK,
  EDIT_SHELVES,
  SET_SEARCH,
  SET_SEARCH_RESULTS,
};
