const TEST_USER = "TEST_USER";
const SET_SIGNED_IN = "SET_SIGNED_IN";
const SIGN_IN_USER = "SIGN_IN_USER";
const SET_PAGE = "SET_PAGE";
const SET_BOOKS = "SET_BOOKS";

export { TEST_USER, SET_SIGNED_IN, SIGN_IN_USER, SET_PAGE, SET_BOOKS };
